ktor {
    deployment {
        host = 0.0.0.0
        port = 1002
        port = ${?PORT}
    }

    application {
        modules = [ ru.gbzlat.ApplicationKt.module ]
    }
}

jwt {
    secret = ${JWT_SECRET}
    issuer = "service-desk"
    audience = "service-desk-client"
    realm = "Service Desk"
}

database {
    hostname = "localhost"
    hostname = ${?DB_HOST}
    port = "5432"
    port = ${?DB_PORT}
    name = "service_desk"
    name = ${?DB_NAME}
    username = "postgres"
    username = ${?DB_USER}
    password = ${DB_PASSWORD}
}

tgbot {
    token = ${?TGBOT_TOKEN}
}
